In [2]:
import pandas as pd
df = pd.read_csv("/content/Iris.csv")

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
# Logistic Regression model and Decision Tree

# Step 1 - Import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [5]:
# Loading the Dataset
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [7]:
df["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [8]:
# Step 3 Prepare the Data
X = df[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
Y = df[["Species"]]

In [9]:
Y

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [10]:
# Split the data into train and test

X_train , X_test , Y_train , Y_test = train_test_split(X  , Y , test_size = 0.2 , random_state = 6)

In [11]:
X_test.shape

(30, 4)

In [12]:
# Create the Logistic Regression model

log_reg = LogisticRegression(max_iter = 100)

log_reg.fit(X_train , Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [13]:
# Decision Tree model

tree_model = DecisionTreeClassifier()

tree_model.fit(X_train , Y_train)

DecisionTreeClassifier()

In [14]:
# Predictions using both models

y_pred_log = log_reg.predict(X_test)

y_pred_tree = tree_model.predict(X_test)

In [15]:
# accuracy_log = log_reg.score(X_test , Y_test)
# accuracy_tree = tree_model.score(X_test , Y_test)

In [16]:
from sklearn.metrics import accuracy_score

accuracy_log = accuracy_score(Y_test , y_pred_log)
accuracy_tree = accuracy_score(Y_test , y_pred_tree)

In [17]:
print("Model Comparision")
print(f"Logistic Regression Accuracy : {accuracy_log * 100:.2f}%")
print(f"Decision Tree Accuracy : {accuracy_tree * 100:.2f}%")

Model Comparision
Logistic Regression Accuracy : 96.67%
Decision Tree Accuracy : 93.33%

In [18]:
from sklearn.metrics import classification_report
print("Detailed Report")
print(classification_report(Y_test , y_pred_log , target_names = ["Iris-setosa" , "Iris-versicolor" , "Iris-virginica"]))

Detailed Report
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.91      1.00      0.95        10
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30